### ISSUE TITLE
make search block smaller

### ISSUE THREAD

**Issue by nileshgulia1** [wzalazar/spotify#2]
make search block smaller and decrease some font sizes..

.Search {
  position: relative;
  background-color: $gray-4;
  padding: <b>12px 2em</b>;

  &__title {
    color: $white;
    font-size: <b>15px</b>;
    letter-spacing: 1px;
    margin-bottom: .5em;
  }

  &__input {
    color: $green-2;
    font-weight:<b> 70</b>;
    font-size:<b> 40p</b>x;
    line-height: 1.2;
    text-shadow: 0 0 0 $white;
    -webkit-text-fill-color: transparent;
    -moz-text-fill-color: transparent;
    -ms-text-fill-color: transparent;
    @media (max-width: $breakpoint-phone) {
      padding: 0;
    }
  }
}
![screenshot from 2017-08-02 01-30-50](https://user-images.githubusercontent.com/22280901/28844467-55e04426-7722-11e7-98c5-e1222b5268b8.png)

**Comment by wzalazar** [comment]
Hi @nileshgulia1 , could you respond this question? 

what's is the issue, or is a improve the UI/UX ?

**Comment by nileshgulia1** [comment]
Its just improve of the UI.  i think it will look good if search box is little bit smaller.have a look at it once,otherwise please ignore.

**Comment by wzalazar** [comment]
@nileshgulia1 ,  nice, I will check your change... if you like create a pull request go ahead!!!

**Comment by nileshgulia1** [comment]
@wzalazar ok
